bot:
  automerge: true
travis:
  secure:
    BINSTAR_TOKEN: Kjq80ro4BDTTshUOkxpHLszVwicPYnyP8o5be5HoepPf+biWAtLxQ7sBkPYWDP1ss7tKredSmEiV4aDlggTCzVtg2Il8KO/MdVSwJIsQmHccUznNoSimz0t9GYwFy54O1lov3B9qFrM17oa77fqkFcqsIh+Jij1rNuUwg2DAXoL3bkRXlRLi8u5sNBy1xu7HiS9tO09nsk3AzGwX2gGARb2VuZr6hP9E5t0lBqc3lqcsithyl8QT5MmAltWABLurFzeJsHn8tD5ikWSTfkhd/OHY6+QTe/Rf4PFVGBo+BV0TNxaWj1V3PMw/IXkLAy3d6rZ8wss95fpb7g0eQq0XvMcqIZQxlRI7o7+86Jo5IsDxB8xeK1Wrw7wRhY0o3u66HK3BPmmirI0NPqWY1uG0vJGKjdZ/dLMaoC75Gn7Yo4ECgT5za3Mr9cmPCpRlUslSW7tMCKcpWdVP5h38W8HnfBDm6qGUUOkpusJYiokXgvrW2G6rGYh2Tzdhi0+bl3NmLHF5rtNwlBb2nEOVcyZlDVr4c8K054R4SuI9ZemE7wEGkL6pZS65NXuxpTzr+xUhCjVjDOjCk2W/X/3Si7KL0vkW7URgvIaes0GkDxfTCKCoTX7p1T4siyGQojS7+FEFV++/kJmcHy3aH5IAUWSyd6zoGoztHbaHGE1JTC0K8FU=
conda_forge_output_validation: true
